"""
verifier_agent.py

Core Verifier Agent: takes (original context, LLM-generated Design Rationale)
and returns a structured decomposition of the DR into individual arguments,
each labeled with one of Zhou et al.'s IHUM categories:
    I = Insightful, H = Helpful, U = Uncertain, M = Misleading

This is the "per-DR aggregate" design (see ../data/raw/DATASET_NOTES.md):
the Verifier does NOT try to match a pre-existing sentence-level ground
truth (none exists in the public dataset). Instead it independently
segments the generated DR into arguments and labels each one; the
per-category counts are then aggregated and compared against Zhou et al.'s
human-labeled per-category COUNTS for the same DR (see evaluate.py).

IMPORTANT: the Verifier is given the ORIGINAL context only (Architecture
Problem + Architecture Decision, i.e. what a human expert reading the
SO/GitHub thread would see) -- NOT the human-written reference Design
Rationale. Feeding the human reference DR would leak the answer key used
to derive the ground-truth IHUM counts.

Supports 3 prompt variants for the ablation study required by the paper:
    - "zero_shot": task description + output schema only
    - "cot":       zero_shot + explicit step-by-step reasoning instruction
    - "few_shot":  cot + one hand-written worked example (synthetic, not
                   drawn from the 100-problem benchmark, to avoid
                   contaminating the evaluation set)

Also supports include_context=False for the context-ablation (Verifier
sees ONLY the generated DR, no original problem/decision) to measure how
much the original context actually contributes.

Every API call is logged (prompt variant, input hash, raw response,
latency, errors) to data/results/api_call_log.jsonl for reproducibility
and debugging, per project guidelines (temperature=0, full call logging).
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from dotenv import load_dotenv
from google import genai
from google.genai import types

PROJECT_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=PROJECT_ROOT / ".env")

DEFAULT_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
DEFAULT_TEMPERATURE = float(os.environ.get("TEMPERATURE", "0"))
LOG_PATH = PROJECT_ROOT / "data" / "results" / "api_call_log.jsonl"

VALID_LABELS = {"Insightful", "Helpful", "Uncertain", "Misleading"}
NFR_CATEGORIES = [
    "performance",
    "security",
    "maintainability",
    "scalability",
    "reliability",
]

PromptVariant = Literal["zero_shot", "cot", "few_shot"]


# --------------------------------------------------------------------------
# Prompt construction
# --------------------------------------------------------------------------

SYSTEM_INSTRUCTION = """You are a Verifier Agent for software architecture Design Rationale (DR).

A "Design Rationale" is an explanation of WHY a given architecture decision is
appropriate for a given architecture problem. You will be shown:
  1. The ORIGINAL architecture problem and the architecture decision that was
     made (this is the ground context — treat it as the only source of truth
     you can check claims against).
  2. A Design Rationale that was GENERATED BY AN LLM for that problem/decision.

Your job is to audit the generated Design Rationale. Concretely:
  a) Segment the generated DR into its individual ARGUMENTS. An "argument" is
     one discrete claim or reason (usually one sentence or bullet point,
     occasionally a short clause) that asserts something about why the
     decision is good, bad, risky, or otherwise relevant.
  b) For EACH argument, decide which of these four categories it belongs to,
     using ONLY the original problem/decision context as your evidence:

     - "Insightful": the argument is correct AND identifies a key/non-obvious
       point that matters for this decision (the kind of point an expert
       would consider central).
     - "Helpful": the argument is correct but is a secondary/supporting point,
       not the crux of the decision.
     - "Uncertain": you cannot verify the argument as true or false from the
       given context — it may be plausible but unconfirmed.
     - "Misleading": the argument is FACTUALLY WRONG or unsupported by (or
       contradicted by) the context, especially if it is stated confidently.
       This is the most dangerous category because a confident wrong
       statement can misdirect a real engineer.

  c) For each argument, provide:
     - "text": the argument, quoted or closely paraphrased from the generated DR
     - "label": one of Insightful | Helpful | Uncertain | Misleading
     - "justification": one or two sentences explaining WHY you assigned this label
     - "evidence_quote": a short verbatim quote from the ORIGINAL problem/decision
       context that supports or contradicts the argument. Use null if no direct
       textual evidence exists (this is common for "Uncertain" arguments).
     - "nfr_related": a list containing zero or more of
       ["performance", "security", "maintainability", "scalability", "reliability"]
       — include any non-functional requirement the argument is discussing, or
       an empty list if none apply.

Output STRICT JSON matching this schema and nothing else (no markdown fences,
no commentary before or after):

{
  "arguments": [
    {
      "text": "...",
      "label": "Insightful" | "Helpful" | "Uncertain" | "Misleading",
      "justification": "...",
      "evidence_quote": "..." | null,
      "nfr_related": ["..."]
    }
  ]
}
"""

FEW_SHOT_EXAMPLE = """
--- WORKED EXAMPLE (synthetic, for calibration only — not part of the dataset you will be scored on) ---

ORIGINAL ARCHITECTURE PROBLEM:
We have a Node.js monolith handling both order processing and email
notifications. Under high load, slow third-party email API calls block the
event loop and delay order processing responses.

ARCHITECTURE DECISION:
Move email sending into a separate worker process that consumes jobs from a
message queue (e.g. RabbitMQ), decoupling it from the main request/response
cycle.

GENERATED DESIGN RATIONALE TO AUDIT:
"Using a message queue removes the blocking email calls from the main
event loop, which directly fixes the reported latency problem under load.
This also improves fault isolation: if the email provider is down, order
processing is unaffected. However, note that Node.js is single-threaded so
this change will have zero effect on CPU-bound order processing tasks
running in the same process, since queues only help with I/O-bound work.
Additionally, RabbitMQ guarantees exactly-once delivery by default, so you
will never see a duplicate email sent to a customer."

EXPECTED OUTPUT:
{
  "arguments": [
    {
      "text": "Using a message queue removes the blocking email calls from the main event loop, which directly fixes the reported latency problem under load.",
      "label": "Insightful",
      "justification": "This is the central mechanism explaining why the decision solves the stated problem (blocking I/O delaying order processing).",
      "evidence_quote": "slow third-party email API calls block the event loop and delay order processing responses",
      "nfr_related": ["performance"]
    },
    {
      "text": "This also improves fault isolation: if the email provider is down, order processing is unaffected.",
      "label": "Helpful",
      "justification": "True and relevant, but a secondary benefit rather than the core reason for the decision.",
      "evidence_quote": null,
      "nfr_related": ["reliability"]
    },
    {
      "text": "Node.js is single-threaded so this change will have zero effect on CPU-bound order processing tasks running in the same process, since queues only help with I/O-bound work.",
      "label": "Uncertain",
      "justification": "Plausible general claim about Node.js concurrency, but the original context never mentions CPU-bound work, so it cannot be verified as relevant either way from the given context.",
      "evidence_quote": null,
      "nfr_related": ["performance"]
    },
    {
      "text": "RabbitMQ guarantees exactly-once delivery by default, so you will never see a duplicate email sent to a customer.",
      "label": "Misleading",
      "justification": "Factually wrong: RabbitMQ's default delivery semantics are at-least-once, not exactly-once, so duplicate emails ARE possible. Stated with unwarranted confidence.",
      "evidence_quote": null,
      "nfr_related": ["reliability"]
    }
  ]
}
--- END OF WORKED EXAMPLE ---
"""

COT_INSTRUCTION = """
Before producing the final JSON, reason step by step INTERNALLY:
1. List every discrete argument you find in the generated DR.
2. For each one, check it against the original problem/decision context.
3. Decide the label and evidence.
Do NOT show this reasoning in your output. Output ONLY the final JSON object.
"""


def build_prompt(
    architecture_problem: str,
    architecture_decision: str,
    generated_dr: str,
    prompt_variant: PromptVariant = "cot",
    include_context: bool = True,
) -> str:
    """Builds the full prompt string sent to Gemini."""
    parts = [SYSTEM_INSTRUCTION]

    if prompt_variant == "few_shot":
        parts.append(FEW_SHOT_EXAMPLE)

    if prompt_variant in ("cot", "few_shot"):
        parts.append(COT_INSTRUCTION)

    if include_context:
        parts.append(
            f"""
--- ORIGINAL ARCHITECTURE PROBLEM ---
{architecture_problem}

--- ARCHITECTURE DECISION ---
{architecture_decision}
"""
        )
    else:
        parts.append(
            "\n--- NOTE: original problem/decision context withheld for this run (context-ablation condition). "
            "Judge each argument only on internal plausibility; use \"Uncertain\" whenever you cannot check a claim without context. ---\n"
        )

    parts.append(
        f"""
--- GENERATED DESIGN RATIONALE TO AUDIT ---
{generated_dr}

--- YOUR OUTPUT (STRICT JSON ONLY) ---
"""
    )
    return "\n".join(parts)


# --------------------------------------------------------------------------
# Gemini call
# --------------------------------------------------------------------------

@dataclass
class VerifierResult:
    arguments: list[dict[str, Any]] = field(default_factory=list)
    raw_response: str = ""
    error: str | None = None
    latency_s: float = 0.0
    resolved_model_version: str | None = None


def _get_client() -> genai.Client:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY not set. Copy .env.example to .env and fill in your key "
            "(https://aistudio.google.com/apikey)."
        )
    return genai.Client(api_key=api_key, http_options={"timeout": 60000})


def _extract_json(raw_text: str) -> dict[str, Any]:
    """Strips markdown code fences if present and parses JSON."""
    text = raw_text.strip()
    fence_match = re.search(r"```(?:json)?\s*(\{.*\})\s*```", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1)
    else:
        # fall back: take the substring between the first '{' and the last '}'
        start = text.find("{")
        end = text.rfind("}")
        if start != -1 and end != -1 and end > start:
            text = text[start : end + 1]
    return json.loads(text)


def _log_call(record: dict[str, Any]) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(LOG_PATH, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def call_verifier(
    architecture_problem: str,
    architecture_decision: str,
    generated_dr: str,
    prompt_variant: PromptVariant = "cot",
    include_context: bool = True,
    model: str = DEFAULT_MODEL,
    temperature: float = DEFAULT_TEMPERATURE,
    max_retries: int = 3,
    request_id: str = "",
) -> VerifierResult:
    """Calls Gemini once for a single DR and returns a parsed VerifierResult.

    Retries on transient errors and on JSON parse failures (asking is not
    re-prompted with a correction message to keep this deterministic /
    reproducible at temperature=0; a parse failure is simply retried as a
    fresh call up to max_retries times).
    """
    prompt = build_prompt(
        architecture_problem,
        architecture_decision,
        generated_dr,
        prompt_variant=prompt_variant,
        include_context=include_context,
    )
    prompt_hash = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:16]
    client = _get_client()

    last_error = None
    for attempt in range(1, max_retries + 1):
        t0 = time.time()
        try:
            resp = client.models.generate_content(
                model=model,
                contents=prompt,
                config=types.GenerateContentConfig(temperature=temperature),
            )
            latency = time.time() - t0
            raw_text = resp.text or ""
            parsed = _extract_json(raw_text)
            arguments = parsed.get("arguments", [])

            # basic schema validation
            for arg in arguments:
                if arg.get("label") not in VALID_LABELS:
                    raise ValueError(f"Invalid label in response: {arg.get('label')!r}")

            # `model` may be a rolling alias (e.g. "gemini-flash-lite-latest") that can
            # silently repoint to a different concrete model over time. Capture the
            # actual resolved version Google served for THIS call so the paper's
            # Experimental Setup can cite the precise model, not just the alias.
            resolved_version = getattr(resp, "model_version", None)

            _log_call(
                {
                    "request_id": request_id,
                    "attempt": attempt,
                    "prompt_variant": prompt_variant,
                    "include_context": include_context,
                    "model": model,
                    "resolved_model_version": resolved_version,
                    "temperature": temperature,
                    "prompt_hash": prompt_hash,
                    "latency_s": latency,
                    "raw_response": raw_text,
                    "status": "ok",
                    "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
                }
            )
            return VerifierResult(
                arguments=arguments,
                raw_response=raw_text,
                latency_s=latency,
                resolved_model_version=resolved_version,
            )

        except Exception as e:  # noqa: BLE001 - log everything, retry loop handles control flow
            latency = time.time() - t0
            last_error = str(e)
            _log_call(
                {
                    "request_id": request_id,
                    "attempt": attempt,
                    "prompt_variant": prompt_variant,
                    "include_context": include_context,
                    "model": model,
                    "temperature": temperature,
                    "prompt_hash": prompt_hash,
                    "latency_s": latency,
                    "raw_response": raw_text if "raw_text" in dir() else "",
                    "status": "error",
                    "error": last_error,
                    "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
                }
            )
            time.sleep(min(2 ** attempt, 20))  # backoff, respects free-tier RPM limits

    return VerifierResult(arguments=[], raw_response="", error=last_error)


def aggregate_counts(arguments: list[dict[str, Any]]) -> dict[str, int]:
    counts = {"Insightful": 0, "Helpful": 0, "Uncertain": 0, "Misleading": 0}
    for arg in arguments:
        label = arg.get("label")
        if label in counts:
            counts[label] += 1
    return counts


if __name__ == "__main__":
    # Quick manual smoke test — run this file directly on a machine with
    # network access to Google's API (NOT inside the Cowork sandbox).
    result = call_verifier(
        architecture_problem="We need to add a new feature to a legacy Rails monolith from a new Django service.",
        architecture_decision="Use Django's pre_init/post_init signals to hook into model construction instead of overriding the constructor.",
        generated_dr="Signals are the officially recommended extension point in Django and avoid fragile constructor overriding. This approach also automatically scales to handle millions of requests per second with zero configuration.",
        prompt_variant="few_shot",
        include_context=True,
        request_id="smoke_test",
    )
    print(json.dumps(result.arguments, indent=2, ensure_ascii=False))
    print("Aggregated counts:", aggregate_counts(result.arguments))
    print("Resolved model version:", result.resolved_model_version)
    if result.error:
        print("ERROR:", result.error)
